version: "3.9"

services:
  db:
    container_name: db_techzone
    image: postgres
    environment:
      POSTGRES_USER: techzone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: techzone
      POSTGRES_PORT: 5432
    volumes:
      - ./techzone/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - techzone

  techzone:
    container_name: service_techzone
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./techzone:/techzone
    ports:
      - "8001:8001"
    depends_on:
      - db
    restart: always
    command: bash entrypoint.sh
    networks:
      - techzone

#  nginx:
#    container_name: nginx_techzone
#    build:
#      context: src/
#      dockerfile: nginx/Dockerfile
#    ports:
#      - "80:80"
#      - "443:443"
#    restart: always
#    volumes:
#      - ./techzone/letsencrypt:/etc/letsencrypt
#      - ./techzone/static:/src/static
#      - ./techzone/media:/src/media
#
#    networks:
#      - techzone

  redis:
    container_name: redis_techzone
    image: redis
    ports:
      - "6379:6379"
    networks:
      - techzone


networks:
  techzone:
    external: true