"""add fields

Revision ID: 998ebd150cbb
Revises: f286ae901c28
Create Date: 2024-05-28 18:01:30.071921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998ebd150cbb'
down_revision = 'f286ae901c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('screen_diagonal', sa.Float(), nullable=False))
    op.add_column('laptops', sa.Column('processor_frequency', sa.Float(), nullable=False))
    op.alter_column('photos', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('smartphones', sa.Column('screen_diagonal', sa.Float(), nullable=False))
    op.add_column('smartphones', sa.Column('processor_frequency', sa.Float(), nullable=True))
    op.add_column('smartwatches', sa.Column('screen_diagonal', sa.Float(), nullable=False))
    op.add_column('tablets', sa.Column('screen_diagonal', sa.Float(), nullable=False))
    op.add_column('tablets', sa.Column('processor_frequency', sa.Float(), nullable=False))
    op.add_column('televisions', sa.Column('screen_diagonal', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('televisions', 'screen_diagonal')
    op.drop_column('tablets', 'processor_frequency')
    op.drop_column('tablets', 'screen_diagonal')
    op.drop_column('smartwatches', 'screen_diagonal')
    op.drop_column('smartphones', 'processor_frequency')
    op.drop_column('smartphones', 'screen_diagonal')
    op.alter_column('photos', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('laptops', 'processor_frequency')
    op.drop_column('laptops', 'screen_diagonal')
    # ### end Alembic commands ###
