"""new fields

Revision ID: a0f2b16a57e2
Revises: 938965787fb4
Create Date: 2024-05-07 17:20:28.404361

"""
from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision = 'a0f2b16a57e2'
down_revision = '938965787fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('usb_ports', sa.String(), nullable=True))
    op.alter_column('laptops', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('laptops', 'memory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('laptops', 'screen_type')
    op.drop_column('laptops', 'usb_devices')
    op.drop_column('order_items', 'is_deleted')
    op.drop_index('ix_photos_url', table_name='photos')
    op.add_column('products', sa.Column('color_hex', sa.String(), nullable=False))
    op.alter_column('smartphones', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('smartphones', 'memory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('smartphones', 'screen_type')
    op.alter_column('smartwatches', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('smartwatches', 'memory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('smartwatches', 'screen_type')
    op.alter_column('tablets', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tablets', 'memory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tablets', 'screen_type')
    op.alter_column('televisions', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('televisions', 'memory',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('televisions', 'screen_type')
    op.add_column('users', sa.Column('photo_url', FileType(storage='../techzone/'), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'photo_url')
    op.add_column('televisions', sa.Column('screen_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('televisions', 'memory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('televisions', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tablets', sa.Column('screen_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('tablets', 'memory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tablets', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('smartwatches', sa.Column('screen_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('smartwatches', 'memory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('smartwatches', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('smartphones', sa.Column('screen_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('smartphones', 'memory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('smartphones', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'color_hex')
    op.create_index('ix_photos_url', 'photos', ['url'], unique=False)
    op.add_column('order_items', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('laptops', sa.Column('usb_devices', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('laptops', sa.Column('screen_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('laptops', 'memory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('laptops', 'memory_ram',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('laptops', 'usb_ports')
    # ### end Alembic commands ###
