"""add is_banner and update fields

Revision ID: a4708168bf16
Revises: da1dd55aa720
Create Date: 2024-06-18 12:29:09.949111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4708168bf16'
down_revision = 'da1dd55aa720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laptops', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('laptops', 'processor_frequency',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('photos', sa.Column('is_banner', sa.Boolean(), nullable=False, default=False, server_default='false'))
    op.create_index(op.f('ix_photos_is_banner'), 'photos', ['is_banner'], unique=False)
    op.alter_column('products', 'discount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('smartphones', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('smartwatches', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tablets', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tablets', 'processor_frequency',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('televisions', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
    op.add_column('laptops', sa.Column('memory_ram_tmp', sa.Numeric(precision=5, scale=3)))
    op.execute('UPDATE laptops SET memory_ram_tmp = memory_ram::NUMERIC(5, 3)')
    op.drop_column('laptops', 'memory_ram')
    op.alter_column('laptops', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('smartphones', sa.Column('memory_ram_tmp', sa.Numeric(precision=5, scale=3)))
    op.execute('UPDATE smartphones SET memory_ram_tmp = memory_ram::NUMERIC(5, 3)')
    op.drop_column('smartphones', 'memory_ram')
    op.alter_column('smartphones', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('smartwatches', sa.Column('memory_ram_tmp', sa.Numeric(precision=5, scale=3)))
    op.execute('UPDATE smartwatches SET memory_ram_tmp = memory_ram::NUMERIC(5, 3)')
    op.drop_column('smartwatches', 'memory_ram')
    op.alter_column('smartwatches', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('tablets', sa.Column('memory_ram_tmp', sa.Numeric(precision=5, scale=3)))
    op.execute('UPDATE tablets SET memory_ram_tmp = memory_ram::NUMERIC(5, 3)')
    op.drop_column('tablets', 'memory_ram')
    op.alter_column('tablets', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('televisions', sa.Column('memory_ram_tmp', sa.Numeric(precision=5, scale=3)))
    op.execute('UPDATE televisions SET memory_ram_tmp = memory_ram::NUMERIC(5, 3)')
    op.drop_column('televisions', 'memory_ram')
    op.alter_column('televisions', 'memory_ram_tmp', new_column_name='memory_ram')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('televisions', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tablets', 'processor_frequency',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tablets', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('smartwatches', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('smartphones', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'discount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_photos_is_banner'), table_name='photos')
    op.drop_column('photos', 'is_banner')
    op.alter_column('laptops', 'processor_frequency',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('laptops', 'screen_diagonal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
    op.add_column('laptops', sa.Column('memory_ram_tmp', sa.Integer))
    op.execute('UPDATE laptops SET memory_ram_tmp = memory_ram::INTEGER')
    op.drop_column('laptops', 'memory_ram')
    op.alter_column('laptops', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('smartphones', sa.Column('memory_ram_tmp', sa.Integer))
    op.execute('UPDATE smartphones SET memory_ram_tmp = memory_ram::INTEGER')
    op.drop_column('smartphones', 'memory_ram')
    op.alter_column('smartphones', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('smartwatches', sa.Column('memory_ram_tmp', sa.Integer))
    op.execute('UPDATE smartwatches SET memory_ram_tmp = memory_ram::INTEGER')
    op.drop_column('smartwatches', 'memory_ram')
    op.alter_column('smartwatches', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('tablets', sa.Column('memory_ram_tmp', sa.Integer))
    op.execute('UPDATE tablets SET memory_ram_tmp = memory_ram::INTEGER')
    op.drop_column('tablets', 'memory_ram')
    op.alter_column('tablets', 'memory_ram_tmp', new_column_name='memory_ram')

    op.add_column('televisions', sa.Column('memory_ram_tmp', sa.Integer))
    op.execute('UPDATE televisions SET memory_ram_tmp = memory_ram::INTEGER')
    op.drop_column('televisions', 'memory_ram')
    op.alter_column('televisions', 'memory_ram_tmp', new_column_name='memory_ram')
