"""add fields in laptop

Revision ID: cd5f7e9bc0df
Revises: c5769c81f851
Create Date: 2024-05-23 17:45:35.644225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5f7e9bc0df'
down_revision = 'c5769c81f851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('processor_model', sa.String(), nullable=False))
    op.add_column('laptops', sa.Column('processor_frequency', sa.Integer(), nullable=False))
    op.add_column('laptops', sa.Column('number_cores', sa.Integer(), nullable=False))
    op.add_column('laptops', sa.Column('number_threads', sa.Integer(), nullable=False))
    op.drop_constraint('orders_id_user_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_id_user_fkey', 'orders', 'users', ['id_user'], ['id'])
    op.drop_column('laptops', 'number_threads')
    op.drop_column('laptops', 'number_cores')
    op.drop_column('laptops', 'processor_frequency')
    op.drop_column('laptops', 'processor_model')
    # ### end Alembic commands ###
